import type { App } from "@/core/create-app";
import { register as registerHomeRoutes } from "@/app/home";
import { register as registerDemoRoutes } from "@/app/demo";
import { register as registerInstallRoutes } from "@/app/install";
import { register as registerAboutRoutes } from "@/app/about";
import { register as registerLogbookRoutes } from "@/app/logbook/index";
import { register as registerInjectExampleDataRoutes } from "@/app/logbook/inject-example-data";
import { register as registerJumpFragmentRoutes } from "@/app/logbook/jump-fragment";
import { register as registerNewJumpRoutes } from "@/app/logbook/jumps/new";
import { register as registerEditJumpRoutes } from "@/app/logbook/jumps/edit";
import { register as registerRemoveJumpGapsRoutes } from "@/app/logbook/jumps/gaps";
import { register as registerImageRoutes } from "@/app/logbook/jumps/from-image";
import { register as registerImageGalleryFragmentRoutes } from "@/app/logbook/jumps/image-gallery-fragment";
import { register as registerAircraftIndexRoutes } from "@/app/logbook/aircraft/index";
import { register as registerNewAircraftRoutes } from "@/app/logbook/aircraft/new";
import { register as registerEditAircraftRoutes } from "@/app/logbook/aircraft/edit";
import { register as registerEditGearRoutes } from "@/app/logbook/gear/edit";
import { register as registerGearIndexRoutes } from "@/app/logbook/gear/index";
import { register as registerNewGearRoutes } from "@/app/logbook/gear/new";
import { register as registerEditJumpTypeRoutes } from "@/app/logbook/jump-types/edit";
import { register as registerJumpTypeIndexRoutes } from "@/app/logbook/jump-types/index";
import { register as registerNewJumpTypeRoutes } from "@/app/logbook/jump-types/new";
import { register as registerEditLocationRoutes } from "@/app/logbook/locations/edit";
import { register as registerLocationIndexRoutes } from "@/app/logbook/locations/index";
import { register as registerNewLocationRoutes } from "@/app/logbook/locations/new";
import { register as registerStatisticsRoutes } from "@/app/logbook/statistics/index";
import { register as registerDetailedStatisticsRoutes } from "@/app/logbook/statistics/detailed";
import { register as registerTransferRoutes } from "@/app/logbook/transfer/index";
import { register as registerExportRoutes } from "@/app/logbook/transfer/export";
import { register as registerServiceWorkerRoutes } from "@/app/service-worker";
import { register as registerStaticAssetRoutes } from "@/app/static-assets";
import { register as registerLokiPreferences } from "@/app/preferences";
import { register as registerLokiAdmin } from "@/app/admin";

export function registerAppRoutes(app: App) {
    registerStaticAssetRoutes(app);
    registerHomeRoutes(app);
    registerDemoRoutes(app);
    registerInstallRoutes(app);
    registerAboutRoutes(app);
    registerLogbookRoutes(app);
    registerInjectExampleDataRoutes(app);
    registerJumpFragmentRoutes(app);
    registerNewJumpRoutes(app);
    registerRemoveJumpGapsRoutes(app);
    registerEditJumpRoutes(app);
    registerImageRoutes(app);
    registerImageGalleryFragmentRoutes(app);
    registerAircraftIndexRoutes(app);
    registerNewAircraftRoutes(app);
    registerEditAircraftRoutes(app);
    registerGearIndexRoutes(app);
    registerNewGearRoutes(app);
    registerEditGearRoutes(app);
    registerJumpTypeIndexRoutes(app);
    registerNewJumpTypeRoutes(app);
    registerEditJumpTypeRoutes(app);
    registerLocationIndexRoutes(app);
    registerNewLocationRoutes(app);
    registerEditLocationRoutes(app);
    registerStatisticsRoutes(app);
    registerDetailedStatisticsRoutes(app);
    registerTransferRoutes(app);
    registerExportRoutes(app);
    registerServiceWorkerRoutes(app);
    registerLokiPreferences(app);
    registerLokiAdmin(app);
}
