import type { App } from "@/app/app";
import { registerAssetRoutes } from "@/route-handlers/assets";
import { register as registerHomeRoutes } from "@/route-handlers/home";
import { register as registerAuthRoutes } from "@/route-handlers/auth/login";
import { register as registerRegistrationRoutes } from "@/route-handlers/auth/register";
import { register as registerLogoutRoutes } from "@/route-handlers/auth/logout";
import { register as registerDemoRoutes } from "@/route-handlers/demo";
import { register as registerReadonlyRoutes } from "@/route-handlers/readonly";
import { register as registerPreferencesRoutes } from "@/route-handlers/preferences/index";
import { register as registerInstallRoutes } from "@/route-handlers/install";
import { register as registerAboutRoutes } from "@/route-handlers/about";
import { register as registerTodoRoutes } from "@/route-handlers/todo";
import { register as registerLogbookRoutes } from "@/route-handlers/logbook/index";
import { register as registerInjectExampleDataRoutes } from "@/route-handlers/logbook/inject-example-data";
import { register as registerJumpFragmentRoutes } from "@/route-handlers/logbook/jump-fragment";
import { register as registerNewJumpRoutes } from "@/route-handlers/logbook/jumps/new";
import { register as registerEditJumpRoutes } from "@/route-handlers/logbook/jumps/edit";
import { register as registerRemoveJumpGapsRoutes } from "@/route-handlers/logbook/jumps/gaps";
import { register as registerImageRoutes } from "@/route-handlers/logbook/jumps/from-image";
import { register as registerImageGalleryFragmentRoutes } from "@/route-handlers/logbook/jumps/image-gallery-fragment";
import { register as registerAircraftIndexRoutes } from "@/route-handlers/logbook/aircraft/index";
import { register as registerNewAircraftRoutes } from "@/route-handlers/logbook/aircraft/new";
import { register as registerEditAircraftRoutes } from "@/route-handlers/logbook/aircraft/edit";
import { register as registerEditGearRoutes } from "@/route-handlers/logbook/gear/edit";
import { register as registerGearIndexRoutes } from "@/route-handlers/logbook/gear/index";
import { register as registerNewGearRoutes } from "@/route-handlers/logbook/gear/new";
import { register as registerEditJumpTypeRoutes } from "@/route-handlers/logbook/jump-types/edit";
import { register as registerJumpTypeIndexRoutes } from "@/route-handlers/logbook/jump-types/index";
import { register as registerNewJumpTypeRoutes } from "@/route-handlers/logbook/jump-types/new";
import { register as registerEditLocationRoutes } from "@/route-handlers/logbook/locations/edit";
import { register as registerLocationIndexRoutes } from "@/route-handlers/logbook/locations/index";
import { register as registerNewLocationRoutes } from "@/route-handlers/logbook/locations/new";
import { register as registerStatisticsRoutes } from "@/route-handlers/logbook/statistics/index";
import { register as registerDetailedStatisticsRoutes } from "@/route-handlers/logbook/statistics/detailed";
import { register as registerTransferRoutes } from "@/route-handlers/logbook/transfer/index";
import { register as registerExportRoutes } from "@/route-handlers/logbook/transfer/export";
import { register as registerAdminRoutes } from "@/route-handlers/admin/index";
import { register as registerLoginAsRoutes } from "@/route-handlers/admin/login-as";
import { register as registerToggleAdminRoutes } from "@/route-handlers/admin/toggle-admin";
import { register as registerToggleReadonlyRoutes } from "@/route-handlers/admin/toggle-readonly";
import { register as registerNewInvitationRoutes } from "@/route-handlers/admin/invitations/new";
import { register as registerEditInvitationRoutes } from "@/route-handlers/admin/invitations/edit";
import { register as registerServiceWorkerRoutes } from "@/route-handlers/service-worker";

let registered = false;

export function registerRoutes(app: App) {
    if (registered) {
        return;
    }
    registerAssetRoutes(app);
    registerHomeRoutes(app);
    registerAuthRoutes(app);
    registerRegistrationRoutes(app);
    registerLogoutRoutes(app);
    registerDemoRoutes(app);
    registerReadonlyRoutes(app);
    registerPreferencesRoutes(app);
    registerInstallRoutes(app);
    registerAboutRoutes(app);
    registerTodoRoutes(app);
    registerLogbookRoutes(app);
    registerInjectExampleDataRoutes(app);
    registerJumpFragmentRoutes(app);
    registerNewJumpRoutes(app);
    registerRemoveJumpGapsRoutes(app);
    registerEditJumpRoutes(app);
    registerImageRoutes(app);
    registerImageGalleryFragmentRoutes(app);
    registerAircraftIndexRoutes(app);
    registerNewAircraftRoutes(app);
    registerEditAircraftRoutes(app);
    registerGearIndexRoutes(app);
    registerNewGearRoutes(app);
    registerEditGearRoutes(app);
    registerJumpTypeIndexRoutes(app);
    registerNewJumpTypeRoutes(app);
    registerEditJumpTypeRoutes(app);
    registerLocationIndexRoutes(app);
    registerNewLocationRoutes(app);
    registerEditLocationRoutes(app);
    registerStatisticsRoutes(app);
    registerDetailedStatisticsRoutes(app);
    registerTransferRoutes(app);
    registerExportRoutes(app);
    registerAdminRoutes(app);
    registerLoginAsRoutes(app);
    registerToggleAdminRoutes(app);
    registerToggleReadonlyRoutes(app);
    registerNewInvitationRoutes(app);
    registerEditInvitationRoutes(app);
    registerServiceWorkerRoutes(app);
    registered = true;
}
